import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getAuth,signInAnonymously} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import {getFirestore,doc,onSnapshot,runTransaction} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import {firebaseConfig,FARM_ID} from './firebase-config.js';
import {calculate,r2} from './calc.js';
const $=id=>document.getElementById(id), money=v=>'Rp'+Math.round(v||0).toLocaleString('id-ID'), num=v=>Number(v||0), fmt=v=>r2(v||0).toLocaleString('id-ID',{maximumFractionDigits:2});
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={feed_buy:'Belanja pakan',feed_use:'Pemakaian pakan',production:'Produksi telur',expense:'Pengeluaran',sale:'Penjualan telur',sale_payment:'Pembayaran piutang',tray_buy:'Belanja tray',tray_loss:'Tray rusak/hilang',flock:'Populasi ayam',other_income:'Pendapatan tambahan'};
let db,ref,records=[],derived,ready=false,working=false;
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',4500);}
function status(t){$('connection').textContent=t;}
function field(name,label,type='number',opts={}){const min=type==='number'?'min="0" step="any"':'';return `<label>${label}<input name="${name}" type="${type}" ${min} ${opts.required===false?'':'required'} ${opts.value!==undefined?'value="'+escape(opts.value)+'"':''} ${opts.placeholder?'placeholder="'+escape(opts.placeholder)+'"':''}></label>`;}
const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
function select(name,label,options){return `<label>${label}<select name="${name}">${options.map(([v,l])=>`<option value="${escape(v)}">${escape(l)}</option>`).join('')}</select></label>`;}
function renderFields(){const t=$('type').value,common=field('date','Tanggal','date',{value:today()});let html=common;
 if(t==='feed_buy')html+=field('name','Nama pakan','text',{placeholder:'Jagung, konsentrat, dll'})+field('qty','Jumlah dibeli (kg)')+field('price','Harga beli (Rp/kg)')+field('shipping','Ongkos kirim pembelian (Rp)', 'number',{value:0});
 if(t==='feed_use')html+=select('name','Jenis pakan',Object.keys(derived?.feedStock||{}).map(k=>[k,k]))+field('qty','Jumlah benar-benar digunakan (kg)')+`<p class="muted">Catat pemakaian bersih setelah sisa pakan diketahui. Bila stok baru dibeli, simpan pembeliannya lebih dahulu.</p>`;
 if(t==='production')html+=field('qty','Telur layak jual dihasilkan (kg)')+field('spoiled','Telur rusak/tidak layak jual (kg)','number',{value:0});
 if(t==='expense')html+=field('name','Nama biaya','text',{placeholder:'Gaji, listrik, obat, dll'})+field('price','Nominal biaya/pembayaran (Rp)')+field('endDate','Tanggal akhir periode biaya (opsional)','date',{required:false})+`<p class="muted">Kosongkan tanggal akhir untuk biaya harian. Untuk listrik/gaji bulanan: tanggal utama = awal periode, tanggal akhir = akhir periode. Jangan masukkan lagi saat membayar.</p>`;
 if(t==='sale')html+=field('name','Nama agen/pembeli','text')+field('qty','Berat telur terjual (kg)')+field('price','Harga jual telur (Rp/kg)')+field('trays','Tray ditukar langsung (buah)','number',{value:0})+field('paid','Dibayar sekarang (Rp)','number',{value:0});
 if(t==='sale_payment'){const opts=records.filter(e=>e.type==='sale').map(e=>[e.id,`${e.date} · ${e.name} · ${fmt(e.qty)} kg`]);html+=select('saleId','Penjualan yang dibayar',opts)+field('price','Jumlah pembayaran (Rp)');}
 if(t==='tray_buy')html+=field('qty','Jumlah tray dibeli (buah)')+field('price','Harga beli (Rp/buah)');
 if(t==='tray_loss')html+=field('qty','Jumlah tray rusak/hilang (buah)')+field('price','Nilai kerugian per tray (Rp)','number',{value:0});
 if(t==='flock')html+=select('direction','Jenis perubahan',[['in','Penambahan ayam'],['out','Ayam mati / afkir']])+field('qty','Jumlah ayam (ekor)');
 if(t==='other_income')html+=field('name','Sumber pendapatan','text',{placeholder:'Pupuk, ayam afkir, dll'})+field('price','Uang diterima (Rp)');
 $('fields').innerHTML=html;
}
function metric(label,value,detail=''){return `<div class="metric"><div class="label">${label}</div><strong>${value}</strong><small>${detail}</small></div>`;}
function current(){const month=$('month').value||today().slice(0,7);const m=derived.monthly[month]||{production:0,feed:0,other:0,allocated:0,sales:0,cogs:0,paid:0,spent:0,otherIncome:0,qtySold:0};return {m,month,hpp:m.production?m.allocated/m.production:null};}
function renderDashboard(){const {m,hpp,month}=current();$('metrics').innerHTML=metric('HPP operasional',hpp===null?'—':money(hpp)+'/kg','Produksi bulan '+month)+metric('Produksi layak jual',fmt(m.production)+' kg','Bulan terpilih')+metric('Biaya pakan digunakan',money(m.feed),'Belanja pakan ≠ biaya pemakaian')+metric('Biaya operasional dialokasikan',money(m.allocated),'Termasuk biaya dari hari tanpa produksi')+metric('Nilai penjualan',money(m.sales),fmt(m.qtySold)+' kg terjual')+metric('Margin penjualan operasional',money(m.sales-m.cogs+m.otherIncome),'Sementara; lihat laporan & catatan');
 const profit=num($('target-profit').value),selling=num($('selling-cost').value),rate=num($('selling-rate').value)/100,market=num($('market-price').value);
 $('price-result').innerHTML=hpp===null?'<strong>HPP belum tersedia</strong><br>Masukkan produksi dan biaya terlebih dahulu.':rate>=1?'<strong>Biaya persentase harus di bawah 100%.</strong>':`Harga target: <strong>${money((hpp+selling+profit)/(1-rate))}/kg</strong><br>Margin pada harga pasar: <b>${money(market*(1-rate)-hpp-selling)}/kg</b>`;
 $('pending-cost').textContent=derived.pendingCost>0?`Ada biaya ${money(derived.pendingCost)} dari hari tanpa produksi yang belum dialokasikan ke telur berikutnya.`:'';
}
function renderStocks(){const feed=Object.entries(derived.feedStock).map(([k,v])=>`${escape(k)}: ${fmt(v.qty)} kg`).join(' · ')||'Belum ada stok pakan';$('stock-cards').innerHTML=metric('Stok pakan',fmt(derived.feedQty)+' kg',feed)+metric('Stok telur',fmt(derived.eggStock)+' kg','Nilai stok: '+money(derived.eggValue))+metric('Tray kosong',fmt(derived.trays)+' buah','Pertukaran setara tidak mengubah total')+metric('Populasi ayam',fmt(derived.flock)+' ekor','Sesuai perubahan yang dicatat')+metric('Piutang agen',money(derived.receivables),'Penjualan belum lunas');
 const filter=$('filter-type').value;$('transactions').innerHTML=[...derived.events].reverse().filter(e=>!filter||e.type===filter).map(e=>`<tr><td>${escape(e.date)}</td><td>${names[e.type]}</td><td>${escape(e.name||'')} ${e.qty!==undefined?'· '+fmt(e.qty):''} ${e.endDate?'(sampai '+escape(e.endDate)+')':''}</td><td>${money(e.value)}</td><td><button class="danger" data-remove="${escape(e.id)}">Hapus</button></td></tr>`).join('')||'<tr><td colspan="5">Belum ada transaksi.</td></tr>';
}
function renderReport(){const {m,month,hpp}=current();const rows=[['Produksi telur layak jual',fmt(m.production)+' kg'],['Biaya pakan yang digunakan',money(m.feed)],['Biaya operasional lainnya',money(m.other)],['Biaya dialokasikan ke produksi',money(m.allocated)],['HPP operasional produksi',hpp===null?'Tidak tersedia':money(hpp)+'/kg'],['Telur terjual',fmt(m.qtySold)+' kg'],['Penjualan telur',money(m.sales)],['Biaya persediaan telur yang terjual (FIFO)',money(m.cogs)],['Pendapatan tambahan',money(m.otherIncome)],['Margin penjualan sebelum biaya operasional yang belum terserap',money(m.sales-m.cogs+m.otherIncome)],['Uang masuk yang dicatat',money(m.paid)],['Uang keluar pembelian dan biaya yang dicatat',money(m.spent)],['Selisih arus kas tercatat',money(m.paid-m.spent)]];
 $('report').innerHTML=`<div class="card"><h3>Periode ${escape(month)}</h3><table class="report-table"><tbody>${rows.map(([k,v])=>`<tr><td>${k}</td><td>${v}</td></tr>`).join('')}</tbody></table><small>Margin penjualan adalah hasil penjualan dikurangi biaya telur terjual, ditambah pendapatan tambahan; tidak memasukkan biaya penjualan yang belum dicatat maupun biaya ayam dan aset. Biaya yang sudah masuk nilai telur tidak dikurangkan kembali.</small></div>`;
}
function render(){try{derived=calculate(records);ready=true;renderFields();renderStocks();renderReport();renderDashboard();status('Firebase tersambung · '+records.length+' transaksi');$('app').classList.remove('hidden');}catch(err){ready=false;status('Data memerlukan perbaikan');toast('Perhitungan tidak valid: '+err.message);}}
async function mutate(update){if(!ready||working)throw Error('Tunggu sinkronisasi data selesai.');working=true;$('save').disabled=true;try{await runTransaction(db,async tx=>{const snap=await tx.get(ref);const old=snap.exists()?(snap.data().records||[]):[];const next=update(old);if(!Array.isArray(next)||next.length>5000)throw Error('Batas versi uji: 5.000 transaksi. Cadangkan data dan pindahkan ke struktur database per-transaksi.');calculate(next);tx.set(ref,{records:next,updatedAt:new Date().toISOString()});});}finally{working=false;$('save').disabled=false;}}
function formData(){const data=Object.fromEntries(new FormData($('transaction-form')).entries());const t=$('type').value;const out={id:crypto.randomUUID(),createdAt:new Date().toISOString(),type:t,date:data.date};for(const [k,v] of Object.entries(data)){if(k==='date'||v==='')continue;out[k]=['qty','price','paid','shipping','spoiled','trays'].includes(k)?Number(v):v;}if(!out.date)throw Error('Tanggal wajib diisi.');if(t==='flock'&&!Number.isInteger(out.qty))throw Error('Jumlah ayam harus bulat.');if(['tray_buy','tray_loss'].includes(t)&&!Number.isInteger(out.qty))throw Error('Jumlah tray harus bulat.');return out;}
function csvCell(x){return '"'+String(x??'').replaceAll('"','""')+'"';}
function download(name,body,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([body],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function wire(){const tabs=[...document.querySelectorAll('[data-tab]')];tabs.forEach(b=>b.onclick=()=>{tabs.forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('hidden',p.id!==b.dataset.tab));});
 $('type').onchange=renderFields;$('month').value=today().slice(0,7);$('month').onchange=()=>{renderDashboard();renderReport();};['target-profit','selling-cost','selling-rate','market-price'].forEach(id=>$(id).oninput=renderDashboard);
 $('filter-type').innerHTML+=[...Object.entries(names)].map(([k,v])=>`<option value="${k}">${v}</option>`).join('');$('filter-type').onchange=renderStocks;
 $('transaction-form').onsubmit=async e=>{e.preventDefault();const b=$('save');try{const event=formData();await mutate(old=>[...old,event]);toast('Transaksi berhasil disimpan.');renderFields();}catch(err){toast('Tidak tersimpan: '+err.message);}};
 $('transactions').onclick=async e=>{const id=e.target.dataset.remove;if(!id||!confirm('Hapus transaksi ini? Penghitungan stok dan HPP akan divalidasi ulang.'))return;try{await mutate(old=>old.filter(x=>x.id!==id));toast('Transaksi dihapus.');}catch(err){toast('Gagal menghapus: '+err.message);}};
 $('export-json').onclick=()=>download('cadangan-hpp-telur-'+today()+'.json',JSON.stringify({version:1,exportedAt:new Date().toISOString(),records},null,2),'application/json');
 $('import-json').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const obj=JSON.parse(await f.text());if(obj.version!==1||!Array.isArray(obj.records))throw Error('Format cadangan tidak sesuai.');calculate(obj.records);if(!confirm('GANTI semua data Firebase dengan isi cadangan? Tindakan ini tidak dapat dibatalkan.'))return;await mutate(()=>obj.records);toast('Cadangan berhasil diimpor.');}catch(err){toast('Impor gagal: '+err.message);}finally{e.target.value='';}};
 $('export-csv').onclick=()=>{const {m,month,hpp}=current();const rows=[['Periode','Produksi kg','Pakan Rp','Operasional lain Rp','Biaya alokasi Rp','HPP Rp/kg','Terjual kg','Penjualan Rp','Biaya telur terjual Rp','Pendapatan lain Rp','Uang masuk Rp','Uang keluar Rp'],[month,m.production,m.feed,m.other,m.allocated,hpp??'',m.qtySold,m.sales,m.cogs,m.otherIncome,m.paid,m.spent]];download('laporan-hpp-'+month+'.csv','\ufeff'+rows.map(x=>x.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8');};
}
async function start(){wire();if(firebaseConfig.apiKey==='ISI_API_KEY'||firebaseConfig.projectId==='ISI_PROJECT_ID'){$('setup').classList.remove('hidden');status('Konfigurasi Firebase belum diisi');return;}
 try{const app=initializeApp(firebaseConfig),auth=getAuth(app);status('Menghubungkan tanpa formulir login…');await signInAnonymously(auth);db=getFirestore(app);ref=doc(db,'farms',FARM_ID);onSnapshot(ref,snap=>{records=snap.exists()?(snap.data().records||[]):[];render();},err=>{status('Firebase gagal: '+err.code);toast(err.message);});}catch(err){status('Koneksi gagal');$('setup').classList.remove('hidden');$('setup').innerHTML=`<h2>Firebase tidak dapat dihubungkan</h2><p>${escape(err.message)}</p><p>Periksa konfigurasi Firebase, Anonymous Authentication, Firestore, dan aturan akses.</p>`;}}
start();
